### PR TITLE
Add LRU and MRU caches.

### PR DESCRIPTION
**Pull request by tmccombs**
Add two more cache clases:
LRU-CACHE for removing the least recently used cache entries.
MRU-CACHE for remove the most recently used cache entries.

### CODE REVIEW

**Comment by ryepup** [comment]
Looks pretty cool. Can you please also update the README.md to mention these in the "types of function-caches currently provided" section?

**Comment by bobbysmith007** [comment]
This looks pretty well wrought.

I have a bit of concern about the key-cached? because it doesn't take into account expiration date when returning an answer.  I am not *sure* that it should or needs to pay attention to the expiration date, but its a thought tugging at my mind.  The way its being used here (after clearing caches) means in practice this probably wont ever be a problem, but I am concerned about that as an interface. in this package.  Not enough concern to not pull the patch, but enough that I wanted to raise the issue incase you had any thoughts.

Otherwise thanks for the patch, and I will apply it shortly

**Comment by tmccombs** [comment]
That's some good feedback. 
I'll change key-cached? to check if the key is expired (and make thunk check if there is a value stored), and update the readme.

**Comment by tmccombs** [comment]
After some thought, I realized that added a check for expiration to key-cached? could cause the dlist and hash table to get out of sync. Specifically in the scenario where a user use clear-cache-partial-arguments when one of the keys is expired. Then the key would be removed from the dlist, but not from the hash table. Later, a reduce-cached-set could be called, due to the size of the hash-table, which then could delete more entries that are still valid, then if it still had the expired entries in the hash-table.  For now I will add a note in the docstring, and remove it from the exports.

**Comment by bobbysmith007** [comment]
I knew that `key-cached?` wouldn't be straightforward... I think your solution is adequate and probably what I would have done given that `key-cached?` is sufficient for its internal use cases.  Thank you for the consideration and patches.

Cheers

**Pull request merged**
